// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Web.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 10, 25, 12, 4, 45, 791, DateTimeKind.Local).AddTicks(2651),
                            PhotoUrl = "x.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 10, 25, 12, 4, 45, 791, DateTimeKind.Local).AddTicks(2653),
                            PhotoUrl = "y.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 10, 25, 12, 4, 45, 791, DateTimeKind.Local).AddTicks(2653),
                            PhotoUrl = "x.jpg"
                        });
                });

            modelBuilder.Entity("Web.Models.BlogLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            Content = "The C# programming language was designed by Anders Hejlsberg from Microsoft in 2000 and was later approved as an international standard by Ecma (ECMA-334) in 2002 and ISO/IEC (ISO/IEC 23270) in 2003. Microsoft introduced C# along with .NET Framework and Visual Studio, both of which were closed-source. At the time, Microsoft had no open-source products. Four years later, in 2004, a free and open-source project called Mono began, providing a cross-platform compiler and runtime environment for the C# programming language. A decade later, Microsoft released Visual Studio Code (code editor), Roslyn (compiler), and the unified .NET platform (software framework), all of which support C# and are free, open-source, and cross-platform. Mono also joined Microsoft but was not merged into .NET",
                            CreatedDate = new DateTime(2022, 10, 25, 12, 4, 45, 791, DateTimeKind.Local).AddTicks(2419),
                            Language = "En",
                            Title = "C# Programming Language"
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 1,
                            Content = "C# proqramlaşdırma dili 2000-ci ildə Microsoft-dan Anders Hejlsberg tərəfindən hazırlanmış və daha sonra 2002-ci ildə Ecma (ECMA-334) və 2003-cü ildə ISO/IEC (ISO/IEC 23270) tərəfindən beynəlxalq standart kimi təsdiq edilmişdir. Microsoft .NET ilə birlikdə C# dilini təqdim etmişdir. Framework və Visual Studio, hər ikisi qapalı mənbə idi. O zaman Microsoft-un açıq mənbə məhsulları yox idi. Dörd il sonra, 2004-cü ildə Mono adlı pulsuz və açıq mənbəli layihə C# proqramlaşdırma dili üçün cross-platform kompilyatoru və iş vaxtı mühitini təmin etdi. On il sonra Microsoft Visual Studio Code (kod redaktoru), Roslyn (tərtibçi) və vahid .NET platformasını (proqram təminatı çərçivəsi) buraxdı, bunların hamısı C#-ı dəstəkləyir və pulsuz, açıq mənbəli və çarpaz platformadır. Mono da Microsoft-a qoşuldu, lakin .NET-ə birləşdirilmədi",
                            CreatedDate = new DateTime(2022, 10, 25, 12, 4, 45, 791, DateTimeKind.Local).AddTicks(2436),
                            Language = "Az",
                            Title = "C# Proqramlaşdırma Dili"
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 1,
                            Content = "Язык программирования C# был разработан Андерсом Хейлсбергом из Microsoft в 2000 году и позже был утвержден в качестве международного стандарта Ecma (ECMA-334) в 2002 году и ISO/IEC (ISO/IEC 23270) в 2003 году. Microsoft представила C# вместе с .NET. Framework и Visual Studio, оба из которых были с закрытым исходным кодом. В то время у Microsoft не было продуктов с открытым исходным кодом. Четыре года спустя, в 2004 году, начался бесплатный проект с открытым исходным кодом под названием Mono, предоставляющий кроссплатформенный компилятор и среду выполнения для языка программирования C#. Десять лет спустя Microsoft выпустила Visual Studio Code (редактор кода), Roslyn (компилятор) и унифицированную платформу .NET (программный фреймворк). Все они поддерживают C# и являются бесплатными, открытыми и кроссплатформенными. Mono также присоединился к Microsoft, но не был объединен с .NET.",
                            CreatedDate = new DateTime(2022, 10, 25, 12, 4, 45, 791, DateTimeKind.Local).AddTicks(2437),
                            Language = "Ru",
                            Title = "C# Язык программирования"
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 2,
                            Content = "Java is a programming language developed by James Gosling of Sun Microsystems and was released in 1995 as a core component of Sun Microsystems. Although this language derives many syntaxes from C and C++ , these derivations include a simpler object model and less low-level possibilities.",
                            CreatedDate = new DateTime(2022, 10, 25, 12, 4, 45, 791, DateTimeKind.Local).AddTicks(2438),
                            Language = "En",
                            Title = "Java Programming Language"
                        },
                        new
                        {
                            Id = 5,
                            BlogId = 2,
                            Content = "Java Sun Microsystems-dən James Gosling tərəfindən hazırlanmış proqramlaşdırma dilidir və 1995-ci ildə Sun Microsystems-in əsas komponenti kimi buraxılmışdır. Bu dil C və C++ dillərindən bir çox sintaksis əldə etsə də , bu törəmələrə daha sadə obyekt modeli və daha az aşağı səviyyəli imkanlar daxildir. Java proqramları , kompüter arxitekturasından asılı olmayaraq istənilən Java Virtual Maşınında ( JVM ) işləyə bilən tipik bayt kodudur.",
                            CreatedDate = new DateTime(2022, 10, 25, 12, 4, 45, 791, DateTimeKind.Local).AddTicks(2440),
                            Language = "Az",
                            Title = "Java Proqramlaşdırma Dili"
                        },
                        new
                        {
                            Id = 6,
                            BlogId = 2,
                            Content = "Java — это язык программирования, разработанный Джеймсом Гослингом из Sun Microsystems и выпущенный в 1995 году в качестве основного компонента Sun Microsystems. Хотя этот язык является производным многих синтаксисов от C и C++ , эти производные включают более простую объектную модель и меньше низкоуровневых возможностей. Приложения Java представляют собой типичный байт -код (файл класса) , который может работать на любой виртуальной машине Java ( JVM ) независимо от.",
                            CreatedDate = new DateTime(2022, 10, 25, 12, 4, 45, 791, DateTimeKind.Local).AddTicks(2441),
                            Language = "Ru",
                            Title = "Java Язык программирования"
                        });
                });

            modelBuilder.Entity("Web.Models.BlogLanguage", b =>
                {
                    b.HasOne("Web.Models.Blog", "Blog")
                        .WithMany("BlogLanguages")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Web.Models.Blog", b =>
                {
                    b.Navigation("BlogLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
